//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layui_admin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> Sorts { get; set; }
        public string Name { get; set; }
        public string EnName { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public string Url { get; set; }
        public string Pic { get; set; }
        public string Description { get; set; }
        public string Contents { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    }
}
