//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layui_admin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_User
    {
        public string Id { get; set; }
        public string NickName { get; set; }
        public string UserName { get; set; }
        public string RealName { get; set; }
        public string PassWord { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        /// <summary>
        /// 性别（1-男；2-女）
        /// </summary>
        public int Sex { get; set; }
        public string Photo { get; set; }
        public int Age { get; set; }
        public Nullable<System.DateTime> Brithday { get; set; }
        public string Introduce { get; set; }
        public string Country { get; set; }
        public Nullable<int> Province { get; set; }
        public Nullable<int> City { get; set; }
        public string Address { get; set; }
        public string LoginIp { get; set; }
        public string RoleID { get; set; }
        public string CreateUserID { get; set; }
        public string CreateUserName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifyUserID { get; set; }
        public string ModifyUserName { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool DeleteMark { get; set; }
    }
}
