//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layui_admin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public Nullable<int> Sorts { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> Hot { get; set; }
        public Nullable<int> Tops { get; set; }
        public Nullable<long> ClickCount { get; set; }
        public Nullable<long> CommentCount { get; set; }
        public string Name { get; set; }
        public string SubName { get; set; }
        public string OutLink { get; set; }
        public string Author { get; set; }
        public string Froms { get; set; }
        public string Pic { get; set; }
        public string Tags { get; set; }
        public string DownloadFiles { get; set; }
        public string Description { get; set; }
        public string Contents { get; set; }
        public string MobContents { get; set; }
        public Nullable<int> IsHidden { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    }
}
