//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Layui_admin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemRoleValue
    {
        public string ID { get; set; }
        public string RoleId { get; set; }
        public string MenuId { get; set; }
        public string Action { get; set; }
        public string Text1 { get; set; }
    }
}
